import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "@/components/StoreProvider";
import NavBar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={` antialiased`}>
          <header>
            <NavBar />
          </header>
          <main className="max-w-[1080px] text-center mx-6 px-5">
            {children}
          </main>
        </body>
      </html>
    </StoreProvider>
  );
}
